redroid-webportal/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get 'download_video', to: 'devices#download', as: 'download'
  get 'video', to: 'static_pages#home', as: 'video'
  get 'videos', to: 'static_pages#home', as: 'videos'

  get 'images/*img', to: 'images#fetch'
  put 'images/*img', to: 'images#upload'
  delete 'delete_video', to: 'devices#delete', as: 'delete'
  resource :devices

  # for any other requests, returns 404
  match "*path", to: "images#error_404", via: :all

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

redroid-webportal/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

redroid-webportal/app/models/device.rb
class Device < ApplicationRecord
  def self.search(dev_id)
    ## do search on disk for all videos with device id
  end
end

redroid-webportal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

redroid-webportal/app/controllers/devices_controller.rb
require 'find'

class DevicesController < ApplicationController
  before_filter :validate_query_params, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    # @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    if params[:search]
      @deviceid = params[:search]
      if File.directory?(file_path = "/home/redroid/video_saves/#{@deviceid}")
        @videos = get_device_directory(@deviceid)
        if (@videos.count == 0)
          flash[:warning] = 'No saved videos found for that device.'
          redirect_to video_path
        else
          @videos.count == 1 ? flash[:info] = "#{@videos.count} video found!" : flash[:info] = "#{@videos.count} videos found!"
        end
        # check for current video streaming
        #if (File.exist? )
      else
        flash[:danger] = "Device: #{@deviceid} not found on the system. Please check ID or contact server administrator."
        redirect_to video_path
      end
    end
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  def validate_query_params
    if params[:search] && params[:search] !~ /\A(\w)+\z/
      flash[:danger] = 'Invalid device name.'
      redirect_to video_path
    end
    if params[:device] && params[:device] !~ /\A(\w)+\z/
      flash[:danger] = 'Invalid device parameter.'
      redirect_to video_path
    end
    if params[:file] && params[:file] !~ /\A(\w|\d)+[_]([-:\w\d])+(.flv)\z/
      flash[:danger] = 'Invalid file parameter.'
      redirect_to video_path
    end
  end

  def download
    if params[:device] && params[:file]
      if File.exist?(file_path = "/home/redroid/video_saves/#{params[:device]}/#{params[:file]}")
        send_file "/home/redroid/video_saves/#{params[:device]}/#{params[:file]}", disposition: 'attachment'
      else
        redirect_to video_path
      end
    end
  end

  def delete
    if params[:device] && params[:file]
      device = params[:file].split('_').first
      if File.exist?(file_path = "/home/redroid/video_saves/#{device}/#{params[:file]}")
        # first remove file from the system
        File.delete(file_path)
        # clean up sym link
        File.delete("/home/redroid/video_saves/vod_links/#{params[:file]}")
        flash[:success] = "Video was successfully deleted."
      else
        flash[:error] = "Video could not be deleted or not found."
      end
    end
    redirect_to devices_path(search: params[:device])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:deviceid, :search, :filepath)
    end

    def video_search(devid)
      # fetch all filenames from the given folder
      return Find.find("/home/redroid/video_saves/#{devid}").map { |path| File.basename path }
    end

    def get_device_directory(device_id)
      if Dir.exist?(file_path = "/home/redroid/video_saves/#{device_id}")
        files = Dir.entries(file_path).select { |e| /\A(\w|\d)+[_]([-:\w\d])+(.flv)\z/ =~ e  }
        files = files.sort_by { |file| File.mtime(file_path + '/' + file) }
        result = []
        files.reverse_each do |file|
          result << { name: file, 
                      size: '%.2f' % (File.size("#{file_path}/#{file}").to_f / 2**20 ) }
        end
        result
      else
        []
      end
    end

end

redroid-webportal/app/controllers/images_controller.rb
class ImagesController < ApplicationController
skip_before_action :verify_authenticity_token
before_action :verify_file_param

# PUT /images/*img <---- param[:img]
def upload
  if File.exists?(file_path = "/home/redroid/motion_detection_images/#{params[:img]}.jpg")
    send_403_forbidden
  else
    File.open(file_path, 'wb') { |file| file.write(request.raw_post)}
    send_200_ok
  end
end

# GET /images
def fetch
  if params[:img] && File.exists?(file_path = "/home/redroid/motion_detection_images/#{params[:img]}.jpg")
    send_file file_path
  else
    send_404_not_found
  end
end

def verify_file_param
  if params[:img] && params[:img] !~ /\A(\w|\d)+\z/
    send_403_forbidden
  end
end

def error_404
    render layout: false
end

private
  def send_403_forbidden
    render nothing: true, status: 403, content_type: 'text/html'
  end

  def send_404_not_found
    render nothing: true, status: 404, content_type: 'text/html'
  end

  def send_200_ok
    render nothing: true, status: 200, content_type: 'text/html'
  end
end

redroid-webportal/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def index
    render :layout => 'layouts/_static_pages'
  end  
end

redroid-webportal/app/helpers/application_helper.rb
module ApplicationHelper
end

redroid-webportal/app/helpers/devices_helper.rb
module DevicesHelper
end

redroid-webportal/app/helpers/images_helper.rb
module ImagesHelper
end

redroid-webportal/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

redroid-webportal/app/views/devices/_form.html.erb
<%= form_for(device) do |f| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deviceid %>
    <%= f.text_field :deviceid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

redroid-webportal/app/views/devices/_video_table.html.erb
<div id="video-table">
  <table class="table">
    <thead class="success">
      <th>
        Video Name:
      </th>
      <th>
        Size:
      </th>
    </thead>
      <% @videos.each do |video| %>
      <tr>
          <td class= "video-title">
            <%= video[:name] %>
          </td>
          <td>
            <%= video[:size].to_s %> MB
          </td>
          <td>
          <%= link_to image_tag("delete_icon.png", id: 'delete-img', size: '30x30'), delete_path(device: "#{locals[:deviceid]}", file: video[:name]), data: { confirm: "Delete video #{video[:name]}?" }, method: :delete %>
          </td>
          <td>
          <%= link_to image_tag("download_icon.png", id: 'download-img', size: '30x30'), download_path(device: "#{locals[:deviceid]}", file: video[:name], target: "_self") %>
          </td>
          <td>
          <%= image_tag("down_arrow_hover.png", id: 'expand-img', size: '30x30', class: 'rotate-image') %>
          </td>
      </tr>
      <tr class="hidden-video" id="<%= video[:name] %>">
        <td>
        </td>
      </tr>
      <% end %>
  </table>
</div>

redroid-webportal/app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

redroid-webportal/app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>
<%= render @files %>
<table>
  <thead>
    <tr>
      <th>Deviceid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.deviceid %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

redroid-webportal/app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

redroid-webportal/app/views/devices/show.html.erb
     <div class="col-lg-6" id="video-table-column">
       <%= render 'video_table', locals: { deviceid: @deviceid } %>
     </div>
     <div class="col-lg-6" id="video-player-column">
       <video id="redroid-video" class="video-js" controls preload="auto" width="640" height="480" data-setup="{}">
         <p class="vjs-no-js">
           To view this video please enable JavaScript, and consider upgrading to a web browser that
           <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
         </p>
       </video>
     </div>

redroid-webportal/app/views/images/error_404.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Redroid 404 Page Not Found</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/x-icon" href=<%= asset_path 'favicon.ico' %> />
  </head>
  <body>
    <div class="row">
      <div class="col-lg-12" align="center">
        <%= image_tag "logo_slate_sky.png", id: 'redroid-logo', style: 'height:60%;width:60%;' %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12" align="center">
        <%= image_tag "404.png", id: '404-image', style: 'height:40%;width:40%;' %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12" align="center">
       <p style="padding: 20px;">The page you were looking for could not be found. Please check your URL.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline" align="center">
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <%= link_to "Video Portal", video_path %>
          </li>
        </ul>
      </div>
    </div>
  </body>
</html>

redroid-webportal/app/views/layouts/_header.html.erb
<div id="header">
  <div class="row">
    <div class="col-12-lg col-12-md col-12-sm">
      <%= image_tag("logo_slate_sky.png") %>
    </div>
  </div>
  <div class="row">
    <div class="col-12-lg col-12-md col-12-sm">
      <h1>Video Portal</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12-lg col-12-md col-12-sm">
      <%= form_tag(devices_path, method: :get) do %>
        <div class="input-group search-control-group">
            <%= text_field_tag :search, nil, class: "input-group-addon form-control", placeholder: 'Enter Device ID' %>
            <span class="input-group-btn">
            <%= submit_tag 'Search', class: 'btn btn-primary' %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

redroid-webportal/app/views/layouts/_static_pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Redroid</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/x-icon" href=<%= asset_path 'favicon.ico' %> />
  </head>
  <body id="index-body">
    <%= yield %>
  </body>
  <script type="text/javascript">
    $('a[href*=\\#]').on('click', function(event){     
      event.preventDefault();
      $('html,body').animate({scrollTop:$(this.hash).offset().top}, 500);
    });
  </script>
</html>

redroid-webportal/app/views/layouts/_tutorial.html.erb
<div class="col-lg-12 bg-success">
  <h1 class="tutorial-slides">Pet Cam</h1>
  <h1 class="tutorial-slides">Bike Cam</h1>
  <h1 class="tutorial-slides">Custom Configuration</h1>
  <h1 class="tutorial-slides">Rules</h1>
  <button class="glyphicon glyphicon-chevron-left" onclick="plusDivs(-1)"></button>
  <button class="glyphicon glyphicon-chevron-right" onclick="plusDivs(1)"></button>
</div>
<script type="text/javascript">
  var slideIndex = 1;
  showDivs(slideIndex);

  function plusDivs(n) {
      showDivs(slideIndex += n);
  };

  function showDivs(n) {
      var i;
      var x = document.getElementsByClassName("tutorial-slides");
      if (n > x.length) {slideIndex = 1} 
      if (n < 1) {slideIndex = x.length} ;
      for (i = 0; i < x.length; i++) {
          x[i].style.display = "none"; 
      }
      x[slideIndex-1].style.display = "block"; 
  };
</script>

redroid-webportal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redroid Web Portal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://vjs.zencdn.net/5.19.0/video-js.css" rel="stylesheet">

    <!-- If you'd like to support IE8 -->
    <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
    <link rel="icon" type="image/x-icon" href=<%= asset_path 'favicon.ico' %> />
  </head>
  <body>
    <div class="container">
      <div class="row" id="header-row">
        <div class="col-lg-12">
          <%= render 'layouts/header' %>
        </div>
      </div>
      <div class="row" id="flash-row">
        <div class="col-lg-12">
          <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <% flash = {} %>
          </div>
      </div>
      <div class="row" id="main-row">
        <%= yield %>
      </div>
        <script src="http://vjs.zencdn.net/5.19.0/video.js"></script>
    </div>
  </body>
</html>

redroid-webportal/app/views/layouts/static_pages/_about.html.erb
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-12 row-header">
      <h2>About</h2>  
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 row-content">
      &nbsp&nbsp&nbsp&nbsp Many Android users have several retired Android phones in a drawer, while a newer phone serves as 
their daily go-to device. But as these retired devices remain packed with valuable tools like 
cameras and sensors, many of these users would benefit from software to repurpose these devices for 
useful tasks. The Redroid project aims to provide a flexible toolset to unlock the full utilization 
of an Android phone's hardware, providing new usefulness to otherwise obsolete devices. Examples 
include: a home security camera, GPS tracker, open garage door detector, bicycle rear-view camera, 
and many more.
    </div>
  </div>
</div>

redroid-webportal/app/views/layouts/static_pages/_contact.html.erb
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-12 row-header">
      <h2>Contact</h2>  
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 row-content">
      <div class="row">
        <div class="col-lg-6">
          <p>
           Redroid consists of 4 team members pursuing bachelor's degrees in Computer Science at the University of Utah. Ordered from left to right are...
          </p>
          <ol>
            <li>
              <b>Matt Madden</b>
                <ul>
                  <li><%= mail_to("themattmadden@gmail.com", "themattmadden@gmail.com") %></li>
                </ul>
            </li>
            <li>
              <b>Greg Smith</b>
                <ul>
                  <li><%= mail_to("greg@gregrsmith.com", "greg@gregrsmith.com") %></li>
                </ul>
            </li>
            <li>
              <b>Derek Johnson</b>
                <ul>
                  <li><%= mail_to("derek.johnson@hsc.utah.edu", "derek.johnson@hsc.utah.edu") %></li>
                </ul>
            </li>
            <li>
              <b>Scott Wells</b>
                <ul>
                  <li><%= mail_to("mail@scottwells.me", "mail@scottwells.me") %></li>
                </ul>
            </li>
          </ol>
        </div>
        <div class="col-lg-6">
          <%= image_tag "redroid_team.jpg", id: "team-image" %>
        </div>
      </div>
    </div>
  </div>
</div>

redroid-webportal/app/views/layouts/static_pages/_header.html.erb
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-12" align="center">
      <h1>
        <%= image_tag "logo_slate_sky.png" %>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h3 align="center">
        <b>Re</b>droid <b>D</b>oes <b>R</b>epurposed, <b>O</b>pen, <b>I</b>nterconnected <b>D</b>evices
      </h3>    
    </div>
  </div>
  <div class="row">
    <ul class="list-inline" align="center">
      <li>
        <%= link_to "About", "#about-row" %>
      </li>
      <li>
        <%= link_to "Tutorial", "#tutorials-row" %>
      </li>
      <li>
        <%= link_to "Contact", "#contact-row" %>
      </li>
    </ul>
  </div>
</div>

redroid-webportal/app/views/layouts/static_pages/_tutorial.html.erb
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-12 row-header">
      <h2>Tutorials</h2>  
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 row-content">
      <button class="glyphicon glyphicon-chevron-left" onclick="plusDivs(-1)" id="tutorial-back-button" disabled></button>
      <button class="glyphicon glyphicon-chevron-right" onclick="plusDivs(1)" id="tutorial-forward-button"></button>
       <div class="tutorial-slides" id="video-1">
          <h3>1. Introduction</h3>
       </div>
       <div class="tutorial-slides" id="video-2">
          <h3>2. Configuration</h3>
       </div>
       <div class="tutorial-slides" id="video-3">
          <h3>3. Streaming Video</h3>
       </div>
       <div class="tutorial-slides" id="video-4">
          <h3>4. Rules</h3>
       </div>
       <div class="tutorial-slides" id="video-5">
          <h3>5. Motion Detection</h3>
       </div>
       <div class="tutorial-slides" id="video-6">
          <h3>6. Location Logging</h3>
       </div>
       <div class="tutorial-slides" id="video-7">
          <h3>7. Bike Cam</h3>
       </div>
       <div id="video-div">
          <%= video_tag "1_Redroid_intro.webm", controls: true, preload: false, autobuffer: true, class: 'tutorial-video', id: 'tutorial-video' %>
       </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var slideIndex = 0;
  var numVideos = 7;
  showDivs(slideIndex);

  function plusDivs(n) {
      videoIndex = slideIndex += n; // mod by number of total videos for wrap-around on button
      console.log(videoIndex);
      showDivs(videoIndex);
      var videoBlock = "";
      switch (videoIndex){
        case 0:
          videoBlock = '<%= video_tag "1_Redroid_intro.webm", preload: "none", controls: true, preload: false, autobuffer: true, class: 'tutorial-video', id: 'tutorial-video' %>';
          break;
        case 1:
          videoBlock = '<%= video_tag "2_Redroid_configuration.webm", preload: "none", controls: true, autobuffer: true, class: 'tutorial-video', id: 'tutorial-video' %>';
          break;
        case 2:
          videoBlock = '<%= video_tag "3_Redroid_streaming_video.webm", preload: "none", controls: true, autobuffer: true, class: 'tutorial-video', id: 'tutorial-video' %>';
          break;
        case 3:
          videoBlock = '<%= video_tag "4_Redroid_rules.webm", preload: "none", controls: true, autobuffer: true, class: 'tutorial-video', id: 'tutorial-video' %>';
          break;
        case 4:
          videoBlock = '<%= video_tag "5_Redroid_motion detection", preload: "none", controls: true, autobuffer: true, class: 'tutorial-video', id: 'tutorial-video' %>';
          break;
        case 5:
          videoBlock = '<%= video_tag "6_Redroid_location_logging.webm", preload: "none", controls: true, autobuffer: true, class: 'tutorial-video', id: 'tutorial-video' %>';
          break;
        case 6:
          videoBlock = '<%= video_tag "7_Redroid_bike_cam.webm", preload: "none", controls: true, autobuffer: true, class: 'tutorial-video bike-cam-video', id: 'tutorial-video' %>';
          break;
      }
      // change video src here
      //$().remove("#tutorial-video");
      videoPlayer = document.getElementById("tutorial-video");
      videoPlayer.pause();
      videoPlayer.setAttribute("src", "");


      $("#video-div").html(videoBlock);
      if(videoIndex + 1 == numVideos){
        $("#tutorial-forward-button").prop("disabled", true);
      }
      else{
        $("#tutorial-forward-button").prop("disabled", false);
      }

      if(videoIndex + 1 == 1){
        $("#tutorial-back-button").prop("disabled", true);
      }
      else {
        $("#tutorial-back-button").prop("disabled", false);
      }

      document.getElementById("tutorial-video").load();
  };

  function showDivs(n) {
      var i;
      var x = document.getElementsByClassName("tutorial-slides"); 
      for (i = 0; i < x.length; i++) {
          x[i].style.display = "none"; 
      }
      x[slideIndex].style.display = "block"; 
  };
</script>

redroid-webportal/app/views/static_pages/index.html.erb
<div class="row" id="main-row">
  <div class="col-lg-2 col-md-2 col-sm-2" id="main-left-margin"></div>
  <div class="col-lg-8 col-md-8 col-sm-8" id="main-column">
    <div class="row" id="title-row">
      <%= render 'layouts/static_pages/header' %>
    </div>
    <div class="row row-spacer" id="spacer-row">
    </div>
    <div class="row" id="about-row">
      <%= render 'layouts/static_pages/about' %>
    </div>
    <div class="row row-spacer" id="spacer-row">
    <%= link_to"Back to Top", "#title-row"%>
    </div>
    <div class="row" id="tutorials-row">
      <%= render 'layouts/static_pages/tutorial' %>
    </div>
    <div class="row row-spacer" id="spacer-row">
    <%= link_to"Back to Top", "#title-row"%>
    </div>
    <div class="row" id="contact-row">
      <%= render 'layouts/static_pages/contact' %> 
    </div>
    <div class="row row-spacer" id="spacer-row">
    <%= link_to"Back to Top", "#title-row"%>
    </div>
  </div>
  <div class="col-lg-2 col-md-2 col-sm-2" id="main-left-margin"></div>
</div>